/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pokemon_firered_-_players_room.glb 
Author: Wesai (https://sketchfab.com/Wesai)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pokemon-firered-players-room-b23b6b253207463c97db2a7092adff74
Title: Pokemon FireRed - Player's Room
*/

import { useGLTF } from "@react-three/drei";
import type { ThreeElements } from "@react-three/fiber";
// import type { GLTF } from "three-stdlib";
// import { Mesh, Material } from "three";

// type GLTFResult = GLTF & {
//   nodes: {
//     base_fireRed_material_0: Mesh;
//     tiles_fireRed_material_0: Mesh;
//     chair_fireRed_material_0: Mesh;
//     table_fireRed_material_0: Mesh;
//     Computer_fireRed_material_0: Mesh;
//     TV_stand_fireRed_material_0: Mesh;
//     TV_fireRed_material_0: Mesh;
//     carpet_A_fireRed_material_0: Mesh;
//     carpet_B_fireRed_material_0: Mesh;
//     bed_fireRed_material_0: Mesh;
//     dresser_fireRed_material_0: Mesh;
//     bookShelf_fireRed_material_0: Mesh;
//     NES_fireRed_material_0: Mesh;
//     railing_fireRed_material_0: Mesh;
//     stairs_fireRed_material_0: Mesh;
//     wall_picture_fireRed_material_0: Mesh;
//     ambient_occlusion_fireRed_material_0: Mesh;
//     title_fireRed_material_0: Mesh;
//   };
//   materials: {
//     fireRed_material: Material;
//   };
// };

export function Model(props: ThreeElements["group"]) {
  const gltf = useGLTF("./pokemon_firered_-_players_room.glb");
  const { nodes, materials } = gltf as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.base_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        geometry={nodes.tiles_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        geometry={nodes.chair_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        geometry={nodes.table_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        geometry={nodes.Computer_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        geometry={nodes.TV_stand_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        geometry={nodes.TV_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        geometry={nodes.carpet_A_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        geometry={nodes.carpet_B_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        geometry={nodes.bed_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        geometry={nodes.dresser_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        geometry={nodes.bookShelf_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        geometry={nodes.NES_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        geometry={nodes.railing_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        geometry={nodes.stairs_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        geometry={nodes.wall_picture_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        geometry={nodes.ambient_occlusion_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        geometry={nodes.title_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
    </group>
  );
}

useGLTF.preload("/pokemon_firered_-_players_room.glb");
